### ISSUE TITLE
persistent storage

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#109]
Some later features will require that things done in one runtime be available at later runtimes: moderation info, etc.

**Comment by joey-colon** [comment]
what kind of technology are you thinking for this? i'm a bit unsure as i don't really know what the problem we're trying to solve with this is

**Comment by c650** [comment]
Could just use MongoDB

**Comment by c650** [comment]
We might want to have some program state remain through reboot, like a list of recent @‘s or something

**Comment by joey-colon** [comment]
yeah nosql sounds fine. you still got your azure credits? 😜

**Comment by c650** [comment]
#131
