### ISSUE TITLE
slowmode command

### ISSUE THREAD

**Issue by honey-joey-colon** [joey-colon/lion#110]
in the event of a timed online test, we don't want to students to be sending messages in the channel while the test is active. we can define a command such as `!slowmode n` where n is the amount of seconds inbetween each message (for an exam, we would want to use the exam duration) / `!slowmode off` to disable.

users with only role of TA or above should be able to activate this command

helpful docs:
https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=setRateLimitPerUser

**Comment by c650** [comment]
Probably also specify a time when slowmode can be turned off automatically

**Comment by serspencer** [comment]
I have the code set up for the use of `!slowmode <time>` i just need to know how you want to go about handling only TA's and up.  Obviously the sloppy way is to manually check the roles of the person issuing the command, but I feel like there is a better way, any thoughts?

**Comment by c650** [comment]
> I have the code set up for the use of !slowmode <time> i just need to know how you want to go about handling only TA's and up. Obviously the sloppy way is to manually check the roles of the person issuing the command, but I feel like there is a better way, any thoughts?

Might be nice to just have it bound to a TA channel.

> Also adding channel type of "Classes" might help so that way it can be limited to the class section.

This exists. See Class Service.

**Comment by c650** [comment]
#188
