### ISSUE TITLE
Report user offense via DM

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#115]
Allows whistleblowers to be anon and lets staff not have to have open DM's.

**Comment by joey-colon** [comment]
did we come up with a concrete way of handling the flow?

**Comment by c650** [comment]
still brainstorming

maybe we take the opportunity to mimic the way that plugins/command handler works, ?? or specify some plugins are dm only, some are both, some are chan only?

**Comment by serspencer** [comment]
Well, you could have a #report channel in which a user issues command !report <user> <report details>.   As soon as the message is sent it gets deleted.  Have the bot just post the content of the message in a dedicated #mod_review channel without posting who sent it.  Biggest issue I see with this however is the message not getting deleted in time and someone still catches it's content.

**Comment by c650** [comment]
can't risk that.

**Comment by serspencer** [comment]
Okay so the lion DM is monitored.  If you DM lion with say a discord.gg link it is reported in botlogs.  So we could just tell users to start their message say !report and then the content of the message goes to a Admin/Mod only reporting channel.
