### ISSUE TITLE
use bot to enforce acknowledgement of CoC

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#151]
Have all users blocked from viewing channels on join -- only CoC channel is visible. Users must acknowledge via message reaction. Thereafter, user is permitted to see other channels.

**Comment by tanndlin** [comment]
I want to tackle this, should I give new users an `unacknowledged` role, and remove it after they react to the CoC?
The unacknwledge role would have to have 0 perms ,then override it in the CoC channel for reactions

**Comment by c650** [comment]
I think it'll be two parts

1. on a guildMemberAdd (just like the default pfp thing), add the role
2. on a message react in CoC, remove the role
  1. wouldn't sit on the specific message waiting for reacts because that times out
  2. instead, https://gist.github.com/koad/316b265a91d933fd1b62dddfcc3ff584#file-discordjs-cheatsheet-js-L244-L251

One caveat I could see is the small chance that due to some lag we have a chain of events:
```
JOIN -> REACT/ACK -> ROLE ADDED -> ???
```
What I'm saying is, if part 1 somehow happens after part 2, then they'd be 'stuck' and would probably have to un-react and re-react.

We may want to set up a Help channel for if this ever happens.

**Comment by tanndlin** [comment]
That's what I was thinking, a 2 parter.
Inside of on react, check if channel is CoC and remove the role, making sure they actually have it. We dont have to check if they reacted to the specific message bc the only one they'd be reacting to is Dr's

**Comment by c650** [comment]
There are more messages there now but it doesn’t really matter.

We will always remove the react as well

**Comment by tanndlin** [comment]
Ok, so check if they reacted in the channel in general? or just on the top message? Cuz there are only 2
Once they do, if they have the role remove it, then remove the reaction?
I figured we could keep the reaction and just have a tally of new members sort of.

w/o the perm to add reacts, a user can still +1 a react that is already there

**Comment by tanndlin** [comment]
Removing it is prob easier

**Comment by c650** [comment]
Sure we can leave the react. What if we also override that Unacknowledged are the only ones who can react in CoC. Less spam that wy.
