### ISSUE TITLE
Register TA via bot

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#159]
Make TA role no longer Mentionable. Instead, moderator can give TA role via bot.

```
!ta add User#0000 cop0000_asdf
``` 
Similar functionality for remove. Either remove all or remove for one class. When we delete the class channels we can reset the TA registrations too.

A student can use

```
!ta ask <some question>
```

And the bot will automatically tag the right people with the question. 

---
This way, if you're a TA in one class and a student in the other, you won't get tagged in both classes.

**Comment by c650** [comment]
In the meantime, we can have a handler that lets people know about the feature. If they mention the TA role, we can remind them that it's soon to be deprecated.

**Comment by c650** [comment]
Make migration script to add to each class channel's topic that `!ta` exists.

**Comment by joey-colon** [comment]
can either persist the relationship of class channel => TA via mongo or if u wanna be hacky have every class channel have a serializable channel topic `TA: ta1 | !ask ta`

**Comment by c650** [comment]
probably want something in the topic for sure.

**Comment by tanndlin** [comment]
That's kinda what I was thinking, because I don't know how to use the DB and that seems scary. Storing the TA's in the topic would be easy

**Comment by c650** [comment]
We can talk about the DB stuff if you'd like.

**Comment by tanndlin** [comment]
Only if you'd prefer it

**Comment by tanndlin** [comment]
Class channels do not have a `ChannelType` how should the user be able to use the command in the channel?

**Comment by c650** [comment]
We would use the class service to see if the channel is in its list

**Comment by joey-colon** [comment]
> Class channels do not have a `ChannelType` how should the user be able to use the command in the channel?

class channels are considered private (`ChannelType.Private`)

**Comment by tanndlin** [comment]
> > Class channels do not have a `ChannelType` how should the user be able to use the command in the channel?
> 
> class channels are considered private (`ChannelType.Private`)

I added a test class through `!addclasschans` and when I used the command with `ChannelType.Private` perms inside the new channel, it said 
`Please use this command in a Private channel`

**Comment by tanndlin** [comment]
https://github.com/joey-colon/lion/blob/46e0f51ab44f39c2fe0acc230360b622c3639574/src/services/channel.service.ts#L38-L39
Here we default to `ChannelType.Private`
https://github.com/joey-colon/lion/blob/46e0f51ab44f39c2fe0acc230360b622c3639574/src/services/channel.service.ts#L55-L58
But when we check perms, we dont check for the channel being private.
Should the last line be `return channelType === ChannelType.Private;`? That allows me to call the plugin in a `Private` Channel

**Comment by c650** [comment]
i see what you mean. @joey-colon  thoughts?
