### ISSUE TITLE
Name Verify

### ISSUE THREAD

**Issue by serspencer** [joey-colon/lion#166]
Upon joining the server, have lion check the username, user-ID, and possibly IP, to help spot secondary and troll accounts.  If it finds one it thinks is similar, assign the user the "unverified" role.

Use a naming blacklist to reference from.

**Comment by c650** [comment]
You can't see IP addr thru discord.

**Comment by serspencer** [comment]
I assume for the same reason for not having local word blacklist we would want to find a source for names as well.  

I see issue when adding our own names, not sure how to handle this.

**Comment by c650** [comment]
closing bcs too complicated imho
