### ISSUE TITLE
Create RoleService for Role-based Permissions

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#187]
This will let us have certain commands exposed in more channels but permission-restricted based on the roles a caller has.

**Comment by c650** [comment]
Resources:
https://discord.js.org/#/docs/main/stable/class/Role

**Comment by gooca** [comment]
How do you want it to work? I can make a service that checks if the user has a role like !help, and if so, allow the user to post when they type !help in a non-bot channel for example. Sound good?

**Comment by c650** [comment]
I don’t get what you mean. It’d be a service that you query about a guild member. 

Say I have a command that only TAs should be able to use. I should be able to ask RoleService if the guild member has TA permissions.

**Comment by gooca** [comment]
Oh ok, I'm assuming we'll just hardcode what commands a TA should be able to run, going to work on this

**Comment by joey-colon** [comment]
within the role service, we can make an enum that contains different role permission levels. ideally it makes most sense to introduce a new property on the plugin abstract class to a default and allow the developer to override it if need be.

when a user runs a command, not only do we check if the user is in the respective channel type, but we also fetch the user's current role level (i think this should be an integer stored as an enum) and check if their role level is larger than the minimum role permission level

**Comment by c650** [comment]
We may also want to think of specifying not just a minimum role but a list of roles.

**Comment by joey-colon** [comment]
when would we want something like that? rather not create a solution for a problem that doesn't exist yet

**Comment by c650** [comment]
fair enough

**Comment by gooca** [comment]
very legal and very cool (done)
