### ISSUE TITLE
Bad blacklist regex leading to incorrect link warnings

### ISSUE THREAD

**Issue by nabakin** [joey-colon/lion#214]
Every time I send the message "group members" in the CS Discord, I get a dm warning from Lion about sharing GroupMe links in the discord. The problem seems to lie with some bad regex in the blacklist handler here. https://github.com/joey-colon/lion/blob/1ea14a31bafe5a577f19b3dca52ec989cd3fb05a/src/app/handlers/blacklist.handler.ts#L14 I'd fix it myself but I don't want to setup a whole instance of the bot to verify everything works correctly.

**Comment by c650** [comment]
Anyone wanna take this?

**Comment by tanndlin** [comment]
I believe /group\s?me($|\W)/ would work
Check to see if there is an end of input or non letter character

**Comment by c650** [comment]
yeah that's what i was thinking

**Comment by tanndlin** [comment]
Only issue is if someone said `groupmes`. It wouldn't detect that

**Comment by tanndlin** [comment]
The regex's in this file seem to target specific links, but the one for group me doesn't, is there a reason for that?

**Comment by CallumCoy** [comment]
Probably just the hate of it GroupMe you could use check it.  my 2cents I think `/group\W?mes?\W/m` would do the trick.  Sample attached.
![Screenshot from 2020-10-27 18-04-06](https://user-images.githubusercontent.com/10034057/97367193-152b3b00-187f-11eb-8358-f857b987be16.png)

**Comment by tanndlin** [comment]
Yeah, I'd create a PR and fix it but idk what a groupme link looks like. I feel like that'd be the ultimate solution

**Comment by c650** [comment]
agree

**Comment by tanndlin** [comment]
`/groupme\.com/` Should work if we only want to target links like the rest of the regex's. Want me to create a PR?

**Comment by c650** [comment]
sure
