### ISSUE TITLE
!users Incorrect number of members

### ISSUE THREAD

**Issue by tanndlin** [joey-colon/lion#218]
![image](https://user-images.githubusercontent.com/39809146/97902169-32428c80-1d0b-11eb-92be-d0dc325fc011.png)

**Comment by tanndlin** [comment]
https://github.com/joey-colon/lion/blob/9beb6f99023120b9105ed970d3a089ed65a328a7/src/app/plugins/users.plugin.ts#L17-L21

Whats the point of the abstraction to `this.container.`?
Why not just `message.guild.users`?

**Comment by c650** [comment]
> Whats the point of the abstraction to this.container.?
> Why not just message.guild.users?

It's debt. Lion is designed to be tied to one guild only.

**Comment by tanndlin** [comment]
Maybe the issue lies within the containerService, could we try `message.guild` instead?
Because `this.container.guildService.get().memberCount` is giving the same number every time
