### ISSUE TITLE
Keep one !market list call inside of #buy_sell_trade

### ISSUE THREAD

**Issue by tanndlin** [joey-colon/lion#243]
Currently Lion sends the user a DM of all the listings, and sends it in #buy_sell_trade if their DMs are closed.
Some people don't want to have to leave the channel to see the listings

A few solutions:

1. Send an updated list to #buy_sell_trade on each `!market add` call, and delete the last list posted.
2. Pin a single list, and just edit that.
3. Send the list on each `!market list` call and delete the old one if something has changed. Don't do anything if there were no changes since last `!market list` call. (Possibly send a link to the last list if nothing changed, which we could queue for deletion after a few seconds as to not spam the channel).

On top of all this, maybe add an optional argument for sending the list as DM regardless, if the user prefers.

**Comment by c650** [comment]
> Send the list on each !market list call and delete the old one if something has changed. Don't do anything if there were no changes since last !market list call. (Possibly send a link to the last list if nothing changed, which we could queue for deletion after a few seconds as to not spam the channel).

Always delete the old one so that the message moves to the bottom of the chat.

> On top of all this, maybe add an optional argument for sending the list as DM regardless, if the user prefers.

solid idea
