### ISSUE TITLE
Market List exceeding 2048 char limit in embed

### ISSUE THREAD

**Issue by tanndlin** [joey-colon/lion#263]
![image](https://user-images.githubusercontent.com/39809146/103820044-94847a00-5039-11eb-9d85-d534f0adaaec.png)

Should be as simple as checking the length of the listings string and splitting into multiple embeds

**Comment by c650** [comment]
This has happened so many times in so many plugins. Maybe it's worth having a standard way to handle it? Maybe wrap `message.send` and then chunk the message?

**Comment by tanndlin** [comment]
I could create a universal function for this, but the market plugin is a special case. I'd prefer to not have a listing span across multiple embeds

**Comment by c650** [comment]
fair enough
