### ISSUE TITLE
mod check in register only checks lowercase

### ISSUE THREAD

**Issue by Kurtoid** [joey-colon/lion#266]
https://github.com/joey-colon/lion/blob/28eee218c67a8c8882810a82aa49ebbf46af1538/src/app/plugins/register.plugin.ts#L27

**Comment by Kurtoid** [comment]
so `!register ALL` works

**Comment by tanndlin** [comment]
Thanks for reporting that :)

**Comment by Kurtoid** [comment]
fixed in #267
