### ISSUE TITLE
Class Check Plugin

### ISSUE THREAD

**Issue by tanndlin** [joey-colon/lion#268]
Make a plugin to see what classes a user is registered for
Probably make command work in user_offenses

**Comment by c650** [comment]
probably bot_logs

**Comment by c650** [comment]
Be mindful of the class list being too large for one message :flushed:

**Comment by tanndlin** [comment]
https://github.com/joey-colon/lion/blob/c9cb4206739b57c7f522aba9d31aba6b4b40e49d/src/app/plugins/checkclasses.plugin.ts#L44-L46
I'll add a check for that aside from this

**Comment by tanndlin** [comment]
fixed by #270
