### ISSUE TITLE
Add first message during addclasschans

### ISSUE THREAD

**Issue by curtishelsel** [joey-colon/lion#272]
We should update this plugin to have a default message for users when the channel is created so they can know the commands of the channel. 

Channel Message:
"Welcome to the class! 

**If it has not been done so already, please post the #class_invite to webcourses to have your classmates join you in this channel.** 

If you are a TA for this course, reach out to a Moderator to have the TA role added to your user and register as the TA in this channel using `!ta register`.  Students in the class can ask the TA a question with a pingable command `!ta ask`.

You are welcome to use any of the audio channels to have study groups as needed and feel free to reach out to any Moderator with questions or concerns for the server. 

Have a great semester!"

Something along those lines, I'm not married to this. It would also be pretty funny if Lion put "first" each time it creates the channel.

**Comment by c650** [comment]
good idea
