### ISSUE TITLE
Joining classes should allow user to pin in channel

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#58]
I think it's good for every student in the class to have pinning permissions.

**Comment by gooca** [comment]
issue closed literally impossible thank you :) TCBA

**Comment by c650** [comment]
probably not impossible

**Comment by gooca** [comment]
@c650 you have to give class users manage message perms since pins aren't a separate perm. So a random class user can delete someone elses message if you give pin perms

**Comment by c650** [comment]
then have a bot command to wrap it

**Comment by gooca** [comment]
users can either pin via typing a message and then doing !pin which will pin their most recent message, or give their message a designated reaction which will be the pin reaction. 

Both do a common discord action that users are familiar with in a hidden, unique to our server way, in an attempt to get around something that discord doesn't support, for something that isn't super needed. 

It's not worth breaking the default Discord experience/behavior for this feature imo

**Comment by c650** [comment]
fair
