### ISSUE TITLE
Fix require links bug

### ISSUE THREAD

**Issue by joey-colon** [joey-colon/lion#74]
Require links handler is deleting messages that include links in them

To reproduce, send this message in a channel that has the handler enabled:
```
test
https://google.com
https://youtube.com
```

**Comment by c650** [comment]
> `private _url_regex: RegExp = /^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/;`

just remove `^` and `$`
