### ISSUE TITLE
stocks command not always working

### ISSUE THREAD

**Issue by c650** [joey-colon/lion#99]
![image](https://user-images.githubusercontent.com/13001055/72184055-7f8cf080-33bd-11ea-921b-7e16b8ab7bce.png)

@brettfazio what did you do??

**Comment by brettfazio** [comment]
I didn't do anything. If you looked at the logs:
`{ Note:
   'Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.' }`

**Comment by brettfazio** [comment]
I could reduce the calls slightly but we are using the same API for both stocks and crypto - hence the reason for hitting the limit.

**Comment by c650** [comment]
https://github.com/joey-colon/lion/blob/9e256aca20a99daca5dcf3932d8891258fc75441/src/app/plugins/price.plugin.ts#L47

See here you’re calling both crypto and stock but not even using crypto if stock comes back right

**Comment by brettfazio** [comment]
Yeah, thats the way we determine if the user is requesting a crypto quote or a stock quote. The way around that would be to locally store all possible crypto quote the user can request - but there's no call to get all those symbols.

**Comment by c650** [comment]
Nah just only hit the Crypto APi if the stock api fails

**Comment by brettfazio** [comment]
Alright

**Comment by c650** [comment]
#101
